# Generated by Django 5.2.1 on 2026-07-22 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="nome"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
            },
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="nome"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "marca",
                "verbose_name_plural": "marcas",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="SKU"),
                ),
                (
                    "descricao_curta",
                    models.CharField(max_length=255, verbose_name="descrição curta"),
                ),
                (
                    "descricao_completa",
                    models.TextField(verbose_name="descrição completa"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="preço"
                    ),
                ),
                (
                    "preco_promocional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="preço promocional",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1, verbose_name="quantidade em estoque"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=3, default=0, max_digits=8, verbose_name="peso"
                    ),
                ),
                (
                    "altura",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="altura"
                    ),
                ),
                (
                    "largura",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="largura",
                    ),
                ),
                (
                    "comprimento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="comprimento",
                    ),
                ),
                (
                    "garantia",
                    models.PositiveIntegerField(default=0, verbose_name="garantia"),
                ),
                (
                    "condicao",
                    models.CharField(
                        choices=[("novo", "Novo"), ("usado", "Usado")],
                        default="novo",
                        max_length=10,
                        verbose_name="condição",
                    ),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=255, verbose_name="tags"),
                ),
                (
                    "estoque",
                    models.PositiveIntegerField(default=1, verbose_name="estoque"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("ativo", "Ativo"),
                            ("pausado", "Pausado"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="data de atualização"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="produtos.categoria",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="produtos.marca",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
            },
        ),
    ]
